apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cdgp-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lVWUpyT3NsUHg3cGlIYTNJUGw5SnUwV1pYRkQwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dURVhNQlVHQTFVRUF3d09NVGN5TGpFMkxqRXdNUzR5TWpNd0hoY05NalF3TkRBNE1Ea3lNVE0yV2hjTgpNelF3TkRBMk1Ea3lNVE0yV2pBWk1SY3dGUVlEVlFRRERBNHhOekl1TVRZdU1UQXhMakl5TXpDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUpTQld1SHpaL1lEQ0dOd0MxNU9SZ1Z3K0U4QVBqYlcKelRLaVBPd3ZBOXpLcFhuNXR3cXVWd2NZRVV2S1NLZUEvR2JIcnNGM25URWgvWG9IcEtnOVJzUmc5d01acmIxRwp3YjlEeUVsSUl2T0Z0aDRYVk5OKy9VcXBZM1FMNTZyT3BmSEVLalVCRmlzNHpIZmxPU1kxeXlBMmU1WUwzZDg0Ckx6aW5DWlpmaEZ5Vm8zaHRrMEdVcEN5SjlBcnlKanQwNU9oYXY2L3RnbTBBUXRTVTFDd1picUt0cHI5bUpCMk0KeEQ1eXVXOVhPMjFubWhILzEyb21HWW50RXltOTJFSkZTMkhuTnE2a1FwUkZwSVNjNTZkc08zeWNXdng1Z08rMApBZFFkcUpjdGdOTHJTeFRyVjR3dHRxNnozWG9KSzdiNEdEbm4rZ211dmpYMkNVakQwOUlhY0o4Q0F3RUFBYU15Ck1EQXdEd1lEVlIwUkJBZ3dCb2NFckJCbDN6QWRCZ05WSFE0RUZnUVVaYWRHWE9kV1NQYzdNZmdFeXpNbWFxazgKYjZzd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEWnFDNWJXSkJZWnloZGlyTWVTd1FzblVnM3hxcjRodjFlbwo3VmpWZ0ZOYzgwQi9MK2E0YWtTOUs1VDlINmJTeFliZnhtbTY4dFNFZ3VJeWw4YisvemsxR2hxVmZTZzZIVER0Ck1hY3VLVGdqL3YzTy8vZ3JYZXRiQXFDTzFlSlhzdkVscVR6LzlwZzVSemdQc2c4U2Y5ZmJjWVhnUW5XWEVmOWwKYmdGN0V2bG50bXZFT2ZFMjQwZ0pva0lyTmRJSDFRa0pCSnBGTVJtZmlDMy9XTDJCa0prSVZTQXlGNjJFcVpuYgpHK1F1ZTdhZ2YzRnVOODdpMTJLS2swdnBUTjRnbXBIektDRDMxeGFjQ05mR0xRYkx2aUJzcUdwMEJsMXdWbXlGCnJ6cWZKYmRIdEE4cnJ5cjJUb0xVcy9tMm1MdWVYM3JyR3pLM0UxdDhSVTY1WCtnZXhnRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://172.16.101.223:9008/mutate
  name: cdgp.siat.ac.cn
  namespaceSelector:
    matchLabels:
      cdgpwebhook: enabled
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
