apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cdgp-webhook-config
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lVS2Z5NzNNcXFJL0ZaZUhGcWFHbUR1bnFtejFrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dURVhNQlVHQTFVRUF3d09NVGN5TGpFMkxqRXdNUzR5TWpNd0hoY05Nak14TVRBeE1EZ3hPREV6V2hjTgpNek14TURJNU1EZ3hPREV6V2pBWk1SY3dGUVlEVlFRRERBNHhOekl1TVRZdU1UQXhMakl5TXpDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUoyeTN6VnQvK3dpS20vM0RqQkVodWtCMHpwOUxTVG8KUFY3NkNhbnVqMHA0dW9Xa3dvMHZ1bWtjTllkNlVrbGRVakZsZTZaZ3ZLblZsL2cxS1ZzM3VJYkZHMldvdW1adgpENmp6bnhxdG1EM0RzVkdwSU1jYzhTY0ZXMG5QcFlDaEpFT1hrVGw2eVhJdkF1cm1vbTJERnE5eXdKUTVvb3ZBCkZrSWZ4SVpDWjJRMVRYWjJBVXJ6R1VuUnZKOWZuMWQxbWRzSFV4d0s5eGJrTGxSK3FPSEVhMTZwajhiVVM4dTkKWithVTlSdXlISG9DcXgwc2JTZm1FRk1IT1h6TlMreDgrQTVyNTNyUFppZjUxKzE2VDRseStIeXlpR0V1ZWRjYwo1Tzh3NUptOXBEMkp1TWEyTEhBR3B1ZEFESjdZRkpPdDI2UVhSVVRhRzVoNmhRL3duSnlGOWwwQ0F3RUFBYU15Ck1EQXdEd1lEVlIwUkJBZ3dCb2NFckJCbDN6QWRCZ05WSFE0RUZnUVViTE1IYVdXaCt4SVV0bFhqNnc0b3FBaVMKZXhJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCeTVxeE94OEl3SEpLSTlmTHhmN1lqNVJxelVZcVVlNERRUApwVDJ5SGhPN2dyaVBzZXB5R1pRR0lHM0pWSFI0Slk2WkF0N3hyblRsaHpwUzhvSWhsTkFkYk9rOEp2WDI3TzJ5CmVocVJOVmlTRWpyNTNuSlE3OElqV2hZT1owczRHbWlJSCtoalpOMVNHenF2dGVXRzJDNFhsV3RtZVNjTUZnaXYKWXB1Z2RuMFhDY21OZWNjN0kyVFdES2diblJrc1o1czlyVGxjZnpuS2ZOdWRuRC9LSExUalRxOHY5TWx1MmxYYwo4Yy9uSTE3eFdUUjFVeDdMK0dKejRPb091QXZwRWZONVZYaGJHMXlJdDdZOHZUMTlEaXlmMXdHQ25CZElQMklnCm5kL2U0aDVPd0hLMFc4bFNJU0taQ3hVRWZDcUNaU1dMRDVJLzJmeWFjYWttbjlCR1pCbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://172.16.101.223:9008/mutate
  name: cdgp.siat.ac.cn
  namespaceSelector:
    matchLabels:
      webhook: enabled
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
